"""add pgvector extension and embedding column to papers

Revision ID: 8a80b8e72227
Revises: 0720aef5b3bb
Create Date: 2026-10-01 15:31:54.456567

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "8a80b8e72227"
down_revision: Union[str, Sequence[str], None] = "0720aef5b3bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column("papers", sa.Column("embedding", Vector(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("papers", "embedding")
    # ### end Alembic commands ###
